INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(1, "Arizona Cardinals", "ARI", 11);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(2, "Atlanta Falcons", "ATL", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(3, "Baltimore Ravens", "BAL", 14);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(4, "Buffalo Bills", "BUF", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(5, "Carolina Panthers", "CAR", 11);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(6, "Chicago Bears", "CHI", 7);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(7, "Cincinnati Bengals", "CIN", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(8, "Cleveland Browns", "CLE", 10);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(9, "Dallas Cowboys", "DAL", 7);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(10, "Denver Broncos", "DEN", 14);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(11, "Detroit Lions", "DET", 5);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(12, "Green Bay Packers", "GB", 10);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(13, "Houston Texans", "HOU", 14);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(14, "Indianapolis Colts", "IND", 14);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(15, "Jacksonville Jaguars", "JAC", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(16, "Kansas City Chiefs", "KC", 6);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(17, "Los Angeles Chargers", "LAC", 5);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(18, "Los Angeles Rams", "LAR", 6);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(19, "Las Vegas Raiders", "LV", 10);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(20, "Miami Dolphins", "MIA", 6);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(21, "Minnesota Vikings", "MIN", 6);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(22, "New England Patriots", "NE", 14);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(23, "New Orleans Saints", "NO", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(24, "New York Giants", "NYG", 11);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(25, "New York Jets", "NYJ", 12);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(26, "Philadelphia Eagles", "PHI", 5);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(27, "Pittsburgh Steelers", "PIT", 9);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(28, "Seattle Seahawks", "SEA", 10);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(29, "San Francisco 49ers", "SF", 9);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(30, "Tampa Bay Buccaneers", "TB", 11);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(31, "Tennessee Titans", "TEN", 5);
INSERT IGNORE INTO `DraftAssistant`.`TEAM`(`ID`,`Name`,`Abbreviation`,`ByeWeek`) VALUES(32, "Washington Commanders", "WAS", 14);