INSERT IGNORE INTO STRENGTH_OF_SCHEDULE (Team, Position, StrengthOfSchedule)
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ARI'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ARI'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ARI'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ARI'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ATL'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ATL'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ATL'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'ATL'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BAL'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BAL'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BAL'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BAL'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BUF'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    1
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BUF'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BUF'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'BUF'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CAR'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CAR'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CAR'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CAR'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CHI'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CHI'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CHI'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CHI'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CIN'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CIN'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CIN'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CIN'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CLE'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CLE'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CLE'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'CLE'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DAL'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DAL'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DAL'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DAL'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DEN'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DEN'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DEN'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DEN'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DET'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DET'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DET'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'DET'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'GB'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'GB'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    1
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'GB'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'GB'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'HOU'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'HOU'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'HOU'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'HOU'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'IND'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'IND'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'IND'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'IND'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'JAC'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'JAC'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'JAC'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'JAC'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'KC'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'KC'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'KC'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'KC'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAC'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAC'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAC'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAC'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAR'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAR'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAR'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LAR'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LV'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LV'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LV'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'LV'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIA'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIA'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIA'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIA'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIN'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIN'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIN'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'MIN'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NE'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NE'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NE'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NE'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NO'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NO'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NO'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NO'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYG'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYG'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYG'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYG'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYJ'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYJ'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYJ'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'NYJ'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PHI'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PHI'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PHI'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PHI'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PIT'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PIT'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PIT'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    1
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'PIT'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SEA'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SEA'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SEA'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SEA'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SF'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SF'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SF'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'SF'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TB'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    2
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TB'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TB'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TB'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TEN'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    5
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TEN'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TEN'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'TEN'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    4
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'WAS'),
    (SELECT ID FROM POSITION WHERE Name = 'QB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'WAS'),
    (SELECT ID FROM POSITION WHERE Name = 'RB'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'WAS'),
    (SELECT ID FROM POSITION WHERE Name = 'WR'),
    3
UNION ALL
SELECT
    (SELECT ID FROM TEAM WHERE Abbreviation = 'WAS'),
    (SELECT ID FROM POSITION WHERE Name = 'TE'),
    2;
