ALTER TABLE `DraftAssistant`.`ADP`
ADD COLUMN `ADPType` INT NULL AFTER `PlayerId`,
ADD INDEX `ADP_TYPE_ID_idx` (`ADPType` ASC) VISIBLE;
;
ALTER TABLE `DraftAssistant`.`ADP`
ADD CONSTRAINT `ADP_TYPE_ID`
  FOREIGN KEY (`ADPType`)
  REFERENCES `DraftAssistant`.`ADP_TYPE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
ALTER TABLE `DraftAssistant`.`ADP`
DROP PRIMARY KEY,
ADD PRIMARY KEY (`PlayerId`, `ADPType`);
;