CREATE TABLE IF NOT EXISTS `RANK` (
  `PlayerId` int NOT NULL,
  `Position` int NOT NULL,
  `Rank` int DEFAULT NULL,
  PRIMARY KEY (`PlayerId`,`Position`),
  KEY `RANK_POSITION_idx` (`Position`),
  CONSTRAINT `RANK_PLAYER` FOREIGN KEY (`PlayerId`) REFERENCES `PLAYER` (`ID`),
  CONSTRAINT `RANK_POSITION` FOREIGN KEY (`Position`) REFERENCES `POSITION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;